### PR TITLE
Minor mod for getNodesForCompIDs

### PR DESCRIPTION
**Pull request by timryanb**
- Minor modifications for smdogroup/tacs#145:
   - Moving method to meshloader
   - Splitting into two methods (one for returning local nodes and one for global)
   - re-implementing addLoadToComps using new method

### CODE REVIEW

**Review by bradenfrigoletto24 — CHANGES_REQUESTED** [review]
Hey @timryanb, sorry for the delay in this, I know it's been a few weeks so hopefully this is all still relevant. I like all the changes you've made; I think it makes the most sense to move these functions to the `meshLoader` class like you've done. 

I only have a small request that I think would make this a little easier for me to use personally. I was wondering if it would be okay to change `getGlobalNodeIDsForComps()` in `pytacs` to something like `getNodeIDsForComps()` and have an input arg that lets you select whether to return global (non-partitioned) or local (partitioned) IDs? The input arg would then just switch which function in the `meshLoader` class gets called. I think both cases could be useful for my use case. 

If you dont think its necessary or useful thats okay with me, I can always get around by just calling the functions in the `meshLoader` class directly. Let me know what you think!

**Comment by timryanb** [comment]
> Hey @timryanb, sorry for the delay in this, I know it's been a few weeks so hopefully this is all still relevant. I like all the changes you've made; I think it makes the most sense to move these functions to the `meshLoader` class like you've done.
> 
> I only have a small request that I think would make this a little easier for me to use personally. I was wondering if it would be okay to change `getGlobalNodeIDsForComps()` in `pytacs` to something like `getNodeIDsForComps()` and have an input arg that lets you select whether to return global (non-partitioned) or local (partitioned) IDs? The input arg would then just switch which function in the `meshLoader` class gets called. I think both cases could be useful for my use case.
> 
> If you dont think its necessary or useful thats okay with me, I can always get around by just calling the functions in the `meshLoader` class directly. Let me know what you think!

Would adding a second pytacs method to expose pymeshloader's `getLocalNodeIDsForComps` method as well work for you? I'm trying to keep the API consistent across the classes, which is why I'd prefer to keep them separate methods (like we do for the similar `getGlobalElementIDsForComps`/`getLocalElementIDsForComps` methods). If this works for you, I'd be happy to expose `getLocalNodeIDsForComps` through pytacs as well

**Comment by timryanb** [comment]
@bradenfrigoletto24, really sorry on my part! I just added a commit with the change I was describing above and meant to push it to my local master fork for you to review on this PR. For some reason it defaulted to your master and committed to it. I'm surprised the repo permissions even allowed me to do that, but regardless, my bad. Hopefully, I didn't mess things up to much on your end...

**Comment by timryanb** [comment]
If you need help resetting your master, let me know. It shouldn't be too hard since you can just force push your local version of the code before my commit

**Comment by bradenfrigoletto24** [comment]
Hey @timryanb. It's not a problem, I have a little message from GitHub warning me about the permissions for this repo that I never did anything about, so it's probably due to that. 

I see what you mean about keeping the API consistent across the board, that makes a lot of sense. Your plan works for me perfectly. 

I will try to do as you suggest, and force push my local repo. Once that's done, I'll let you know and you can make your commits. Then we'll see about wrapping this all up.

**Comment by bradenfrigoletto24** [comment]
@timryanb alright I just force pushed and it looks like its reset things properly.

**Comment by timryanb** [comment]
Sounds good, I just added the new API to my master. If the changes work for you we can get this PR merged and then merge your original PR into smdogroup/tacs

**Review by bradenfrigoletto24 — APPROVED** [review]

**Pull request merged**
